### ISSUE TITLE
Проблема с NotesList

### ISSUE THREAD

**Issue by ignatevdev** [mb24dev/amocrm#2]
В AmoGetMethod есть лишний if, который не дает указать параметр type, необходимый в NotesList
`if($key !== 'domain' && $key !== 'type' && $key !== 'url' && isset($value) && !is_array($value))`

Уберите `$key !== 'type'`, чтобы у других людей не возникало с этим проблем

**Comment by d3fvxl** [comment]
Спасибо большое за обратную связь. В скором времени я выложу новую версию, реализованную на Guzzle и учту Ваше замечание.
